// artworks.js — 엑셀 56작품 데이터 (자동 생성)
const ARTWORKS = {
  korea: [
    { id:'goguryeo-hunt', title:'수렵도', artist:'작자미상(고구려 무용총 벽화)', year:'5세기 전반', country:'고구려',
      url:'images/hunting.jpg',
      desc:'고구려 무용총에 그려진 수렵도입니다. 말을 탄 사냥꾼이 힘차게 활을 당기는 역동적인 장면으로, 고구려인의 용맹함과 생동감 넘치는 필치가 느껴집니다.' },
    { id:'goguryeo-ssireum', title:'씨름도', artist:'작자미상(고구려 각저총 벽화)', year:'5세기 전반', country:'고구려',
      url:'images/ssireum-goguryeo.jpg',
      desc:'고구려 각저총에 그려진 벽화입니다. 두 인물이 씨름하는 모습과 구경꾼이 묘사되어 있으며, 고구려 시대 씨름 문화와 풍속을 생생하게 전해줍니다.' },
    { id:'mongyu', title:'몽유도원도', artist:'안견', year:'1447', country:'조선',
      url:'images/mongyudowondo.jpg',
      desc:'세종대왕의 셋째 아들 안평대군이 꿈에서 본 도원을 안견이 3일만에 그린 작품입니다. 현실과 이상세계를 대비적으로 표현한 조선 초기 최고의 산수화입니다.' },
    { id:'chochungdo', title:'초충도', artist:'신사임당', year:'16세기', country:'조선',
      url:'images/chochungdo.jpg',
      desc:'율곡이이의 어머니이자 뛰어난 예술가 신사임당의 대표작입니다. 풀과 벌레를 섬세하게 표현하였습니다.' },
    { id:'geumgang', title:'금강전도', artist:'정선(겸재)', year:'1734', country:'조선',
      url:'images/geumgang.jpg',
      desc:'진경산수화의 대가 겸재 정선이 금강산 전경을 담은 걸작입니다. 실제 경치를 보고 그린 진경산수화로, 웅장한 금강산의 모습을 위에서 아래로 내려다본 구도로 표현했습니다.' },
    { id:'ssireum', title:'씨름', artist:'김홍도(단원)', year:'18세기', country:'조선',
      url:'images/ssireum.jpg',
      desc:'조선 후기 풍속화의 대가 단원 김홍도의 대표작입니다. 씨름꾼과 원형으로 앉은 구경꾼들의 다양한 표정이 생생하게 묘사되었습니다.' },
    { id:'dano', title:'단오풍정', artist:'신윤복(혜원)', year:'18세기 말~19세기 초', country:'조선',
      url:'images/dano.jpg',
      desc:'조선 후기 풍속화가 혜원 신윤복의 대표작입니다. 단오절에 그네를 타는 여인들과 이를 몰래 바라보는 선비들의 모습을 생동감 있게 표현했습니다.' },
    { id:'woljeongin', title:'월하정인', artist:'신윤복(혜원)', year:'18세기 말~19세기 초', country:'조선',
      url:'images/wolha.jpg',
      desc:'달빛 아래 연인이 은밀히 만나는 장면을 묘사한 조선 후기 혜원 신윤복의 풍속화입니다.' },
    { id:'miindo', title:'미인도', artist:'신윤복(혜원)', year:'18세기 말~19세기 초', country:'조선',
      url:'images/miindo.jpg',
      desc:'혜원 신윤복의 미인도는 조선 후기 여성의 아름다움을 섬세하게 표현한 작품입니다. 치마저고리를 입은 여인의 우아한 자태와 정교한 의복 묘사가 특징입니다.' },
    { id:'sehando', title:'세한도', artist:'김정희(추사)', year:'1844', country:'조선',
      url:'images/Sehando.jpg',
      desc:'실학자이자 서예가 추사 김정희가 제주도 유배 중에 그린 작품입니다. 소나무와 잣나무 두 그루를 단순하게 표현하여 변치 않는 절개와 우정을 담았습니다.' },
    { id:'mudong', title:'무동', artist:'김홍도(단원)', year:'18세기', country:'조선',
      url:'images/mudong.jpg',
      desc:'조선 후기 풍속화의 대가 단원 김홍도의 작품입니다. 악사들의 연주에 맞춰 어린 무동이 춤을 추는 생동감 있는 장면을 담았습니다.' },
    { id:'seodang', title:'서당', artist:'김홍도(단원)', year:'18세기', country:'조선',
      url:'images/seodang.jpg',
      desc:'김홍도의 단원풍속도첩 중 하나로 서당에서 글공부하는 아이들의 모습을 담았습니다. 훈장께 꾸중을 들은 아이가 울음을 터뜨리는 장면이 익살스럽게 표현되어 있습니다.' },
    { id:'tajak', title:'타작', artist:'김홍도(단원)', year:'18세기', country:'조선',
      url:'images/tajak.jpg',
      desc:'김홍도의 풍속화로 가을 추수 때 볏단을 타작하는 농민들의 모습을 담았습니다. 힘차게 도리깨질하는 농부들과 지주로 보이는 인물이 대비를 이루며 조선 후기 농촌 사회를 생동감 있게 보여줍니다.' },
    { id:'yunduseo', title:'자화상(윤두서)', artist:'윤두서(공재)', year:'1710년경', country:'조선',
      url:'images/yunduseo.jpg',
      desc:'조선 후기 화가 윤두서의 자화상으로 우리나라 최초의 사실적 자화상입니다. 강렬한 눈빛과 세밀한 수염 묘사가 특징이며 얼굴만 집중적으로 표현한 독특한 구성이 인상적입니다. 국보 제240호로 지정되어 있습니다.' },
    { id:'puppies', title:'모견도(강아지)', artist:'이암', year:'16세기', country:'조선',
      url:'images/mogyeondo.jpg',
      desc:'조선 중기 화가 이암이 그린 영모화입니다. 나무 아래 어미개와 강아지들이 모습을 섬세하게 묘사하였습니다.' },
    { id:'desertedmountain', title:'공산무인도', artist:'최북(호생관)', year:'18세기', country:'조선',
      url:'images/gongsanmuindo.jpg',
      desc:'조선 후기 화가 최북의 대표작입니다. 나무 아래 빈 정자의 모습이 보이며 왼쪽에 계곡물이 흐른다. 중앙에 낙관 두개와 큰 글씨가 조화를 이루고 있다.' },
    { id:'plumblossom', title:'묵매도', artist:'어몽룡(설곡)', year:'16~17세기', country:'조선',
      url:'images/mukmaedo.jpg',
      desc:'조선 중기 문인화가 어몽룡의 대표작으로 먹으로 그린 매화 그림입니다. 간결하고 힘찬 필치로 매화의 기품을 표현했습니다.' },
    { id:'hawk', title:'호취도', artist:'장승업(오원)', year:'19세기', country:'조선',
      url:'images/hochwido.jpg',
      desc:'조선 말기 화가 오원 장승업의 대표작입니다. 강렬한 눈매와 날카로운 발톱을 가진 매의 모습을 힘차고 사실적으로 표현했습니다.' },
    { id:'inwangjesaekdo', title:'인왕제색도', artist:'정선(겸재)', year:'1751', country:'조선',
      url:'images/inwangjesaekdo.jpg',
      desc:'진경산수화의 대가 겸재 정선의 대표작입니다. 비가 갠 뒤 안개에 싸인 서울 인왕산의 웅장한 모습을 표현했습니다. 먹의 농담을 자유롭게 구사한 대담한 구도가 특징입니다.' },
    { id:'pajukdo', title:'파적도(야묘도추)', artist:'김득신(긍재)', year:'18세기', country:'조선',
      url:'images/pajeokdo.jpg',
      desc:'조선 후기 풍속화가 김득신의 대표작입니다. 고양이가 병아리를 채어가자 놀란 사람들이 허둥대는 해학적인 장면을 담았습니다. 순간의 동작을 포착한 생생한 묘사와 익살스러운 표정이 인상적입니다.' },
    { id:'bamboo', title:'풍죽도', artist:'이정(탄은)', year:'16~17세기', country:'조선',
      url:'images/pungjukdo.jpg',
      desc:'조선 중기 묵죽화의 대가 이정의 대표작입니다. 바람에 휘어지는 대나무를 먹으로 힘차게 표현했습니다. 군자의 절개를 상징하는 대나무를 이정만의 독자적인 화풍으로 담아낸 조선 묵죽화의 최고 걸작입니다.' },
    { id:'yeongtong', title:'영통동구도', artist:'강세황(표암)', year:'1757', country:'조선',
      url:'images/yeongtongdonggudo.jpg',
      desc:'조선 후기 문인화가이자 표암 강세황의 작품입니다. 서양화의 투시도법과 음영법을 도입하여 묘사했습니다. 서양화 기법을 접목한 조선 최초의 작품 중 하나로 평가받습니다.' },
    { id:'gosagwansu', title:'고사관수도', artist:'강희안(인재)', year:'15세기', country:'조선',
      url:'images/gosagwansudo.jpg',
      desc:'조선 초기 강희안의 대표작입니다. 깎아지른 절벽을 배경으로 바위 위에 앉아 물을 바라보는 선비의 모습을 담았습니다.' },
    { id:'dalma', title:'달마도', artist:'김명국(연담)', year:'17세기', country:'조선',
      url:'images/dalma.jpg',
      desc:'조선 중기 화가 김명국의 대표작으로 불교의 선종을 창시한 달마대사를 그린 인물화입니다. 거칠고 힘찬 필치로 달마의 강인한 정신을 표현했으며, 조선 시대 선종화의 걸작으로 꼽힙니다.' },
    { id:'yuap', title:'유압도', artist:'홍세섭(석창)', year:'19세기', country:'조선',
      url:'images/yuapdo.jpg',
      desc:'전통적인 영모화(새와 짐승을 그린 그림) 소재를 부감법 구도(위에서 내려다보는 시점)와 추상적인 배경 표현, 간략하고 속도감 있는 필치로 그려 현대적인 수채화를 연상시킵니다. 조선 후기에는 홍세섭과 같은 이색적인 화풍이 유행하였습니다.' },
    { id:'wolmae', title:'월매도', artist:'어몽룡', year:'16~17세기', country:'조선',
      url:'images/wolmaedo.jpg',
      desc:'조선 중기 문인화가 어몽룡의 대표작입니다. 달빛 아래 피어난 매화를 먹으로 그린 묵매화(墨梅畵)로, 간결하고 힘찬 필치로 매화의 기품을 표현했습니다.' },
    { id:'gangsanmujiindo', title:'강산무진도', artist:'이인문', year:'18~19세기', country:'조선',
      url:'images/gangsanmujindo.jpg',
      desc:'조선 후기 화가 이인문의 대표작으로 산과 강이 끝없이 이어지는 장대한 자연 풍경을 담은 두루마리 그림입니다. 856cm에 달하는 화면에 사계절 변화와 인간 생활을 담아냈습니다.' },
    { id:'sparrows', title:'참새와 고양이(묘작도)', artist:'변상벽(화재)', year:'18세기', country:'조선',
      url:'images/chamsae-goyangi.jpg',
      desc:'조선 후기 도화서 화원 변상벽이 그린 한 쌍의 고양이와 다급하게 지저귀는 참새 떼의 모습입니다. 섬세한 필치로 실감나게 묘사하였습니다.' }
  ],
  world: [
    { id:'monalisa', title:'모나리자', artist:'레오나르도 다빈치', year:'1503~1505', country:'이탈리아',
      url:'images/mona-lisa.jpg',
      desc:'이탈리아 르네상스의 거장 레오나르도 다빈치가 그린 세계에서 가장 유명한 초상화입니다. 신비로운 미소와 스푸마토 기법으로 수백 년간 사람들을 매료시켜 왔습니다.' },
    { id:'lastsupper', title:'최후의 만찬', artist:'레오나르도 다빈치', year:'1495~1498', country:'이탈리아',
      url:'images/last-supper.jpg',
      desc:'레오나르도 다빈치가 밀라노 수도원 식당 벽에 그린 대형 벽화입니다. 예수가 "너희 중 한 명이 나를 배신할 것이다"라고 말하는 순간을 포착했습니다.' },
    { id:'venus', title:'비너스의 탄생', artist:'산드로 보티첼리', year:'1484~1486', country:'이탈리아',
      url:'images/birth-of-venus.jpg',
      desc:'이탈리아 르네상스 화가 보티첼리의 걸작으로 사랑의 여신 비너스가 조개껍데기에서 태어나는 장면을 묘사했습니다. 고대 신화를 주제로 한 최초의 대형 캔버스 작품 중 하나입니다.' },
    { id:'athens', title:'아테네 학당', artist:'라파엘로 산치오', year:'1509~1511', country:'이탈리아',
      url:'images/school-of-athens.jpg',
      desc:'교황 율리오 2세의 주문으로 라파엘로가 그린 프레스코화입니다. 플라톤과 아리스토텔레스를 중심으로 고대 그리스 철학자들이 모여 있는 장면으로, 르네상스 정신의 집대성입니다' },
    { id:'pearlgirl', title:'진주 귀걸이를 한 소녀', artist:'요하네스 페르메이르', year:'1665년경', country:'네덜란드',
      url:'images/pearlgirl.jpg',
      desc:'"북방의 모나리자"라 불리는 걸작입니다. 신비로운 눈빛과 반짝이는 진주 귀걸이가 특징이며 소녀의 정체는 아직도 미스터리입니다.' },
    { id:'nightwatch', title:'야경', artist:'렘브란트 판 레인', year:'1642', country:'네덜란드',
      url:'images/night-watch.jpg',
      desc:'렘브란트의 대표작으로 야간 순찰을 나서는 민병대의 모습을 역동적으로 표현했습니다. 빛과 그림자의 극적인 대비가 바로크 회화의 특징을 잘 보여줍니다.' },
    { id:'starrynight', title:'별이 빛나는 밤', artist:'빈센트 반 고흐', year:'1889', country:'네덜란드',
      url:'images/starry-night.jpg',
      desc:'반 고흐가 생레미 드 프로방스 요양원에서 그린 걸작입니다. 소용돌이치는 밤하늘과 빛나는 별들, 고요한 마을의 대비가 인상적입니다.' },
    { id:'sunflowers', title:'해바라기', artist:'빈센트 반 고흐', year:'1888년 8월', country:'네덜란드',
      url:'images/sunflowers.jpg',
      desc:'반 고흐가 남프랑스 아를에서 폴 고갱을 맞이하기 위해 그린 연작입니다. 황금빛 해바라기들을 독특한 임파스토 기법으로 표현하여 생명력과 기쁨을 담았습니다.' },
    { id:'waterlilies', title:'수련', artist:'클로드 모네', year:'1906', country:'프랑스',
      url:'images/water-lilies.jpg',
      desc:'인상주의 거장 모네가 지베르니 정원의 연못을 그린 연작입니다. 빛과 색의 변화에 집중하여 수면과 수련을 몽환적으로 표현했습니다.' },
    { id:'scream', title:'절규', artist:'에드바르 뭉크', year:'1893', country:'노르웨이',
      url:'images/scream.jpg',
      desc:'노르웨이 화가 에드바르 뭉크의 대표작으로, 핏빛 하늘 아래 다리 위에서 귀를 막고 절규하는 인물을 표현했습니다. 인간의 불안과 공포를 강렬하게 담아낸 표현주의의 대표작입니다.' },
    { id:'greatwave', title:'가나가와 해변의 큰 파도', artist:'가쓰시카 호쿠사이', year:'1831년경', country:'일본',
      url:'images/great-wave.jpg',
      desc:'에도 시대 목판화 거장 호쿠사이의 "후지산 36경" 연작 중 가장 유명한 작품입니다. 거대한 파도와 후지산의 대비가 인상적이며 서양 예술가에도 큰 영향을 미쳤습니다.' },
    { id:'plum', title:'홍백매화도', artist:'오가타 고린', year:'1714~1716년경', country:'일본',
      url:'images/red-white-plum.jpg',
      desc:'에도 시대 화가 오가타 고린의 대표작입니다. 흐르는 물과 홍백 매화나무를 대담하고 장식적으로 표현한 금박 병풍화로, 일본 린파 화풍의 최고 걸작으로 꼽힙니다.' },
    { id:'rain-bridge', title:'오하시 다리의 소나기', artist:'우타가와 히로시게', year:'1857', country:'일본',
      url:'images/ohashi-rain.jpg',
      desc:'우타가와 히로시게의 목판화 걸작으로 소나기 내리는 다리 위 사람들의 모습을 담았습니다. 대각선 빗줄기와 움직이는 인물들의 묘사가 인상적이며, 인상주의 화가들에게 큰 영향을 주었습니다.' },
    { id:'liberty', title:'민중을 이끄는 자유의 여신', artist:'외젠 들라크루아', year:'1830', country:'프랑스',
      url:'images/Liberty-Leading-the-People.jpg',
      desc:'1830년 프랑스 7월 혁명에서 국민들이 절대왕정에 맞서 자유와 권리를 위해 싸우는 모습을, 자유를 상징하는 여성을 중심으로 표현한 낭만주의 대표작이다.' },
    { id:'fuchun', title:'부춘산거도', artist:'황공망', year:'1350', country:'중국',
      url:'images/fuchun-mountains.jpg',
      desc:'원나라 화가 황공망이 3~4년에 걸쳐 완성한 산수화의 걸작입니다. 부춘강 주변의 경치를 담백하고 자유로운 필치로 표현했으며, 중국 산수화의 최고 작품 중 하나로 꼽힙니다.' },
    { id:'grandejatte', title:'그랑자트 섬의 일요일 오후', artist:'조르주 쇠라', year:'1884~1886', country:'프랑스',
      url:'images/la-grande-jatte.jpg',
      desc:'신인상주의 화가 조르주 쇠라의 대표작으로 점묘화 기법의 걸작입니다. 파리 근교 그랑자트 섬에서 여가를 즐기는 시민들의 모습을 수백만 개의 점으로 표현했습니다.' },
    { id:'impression', title:'인상, 해돋이', artist:'클로드 모네', year:'1872', country:'프랑스',
      url:'images/impression-sunrise.jpg',
      desc:'인상주의 운동의 출발점이 된 모네의 걸작입니다. 프랑스 르아브르 항구의 이른 아침 안개 속 해돋이를 빠른 붓놀림으로 포착했습니다. 이 작품의 제목에서 "인상주의"라는 미술 사조의 이름이 유래했습니다.' },
    { id:'danceclass', title:'무용 교실', artist:'에드가 드가', year:'1874', country:'프랑스',
      url:'images/dance-class.jpg',
      desc:'인상주의 화가 에드가 드가의 대표작으로 파리 오페라 극장의 발레 연습 장면을 담았습니다. 어린 발레리나들이 선생님께 지도받는 모습을 독특한 시각으로 포착했습니다. 빛의 효과와 움직임의 순간을 탁월하게 표현한 작품입니다.' },
    { id:'olympia', title:'올랭피아', artist:'에두아르 마네', year:'1863', country:'프랑스',
      url:'images/olympia.jpg',
      desc:'근대 회화의 아버지 에두아르 마네의 대표작입니다. 누드 여인을 비신화적으로 직접 표현하여 발표 당시 엄청난 논란을 일으켰습니다. 전통 누드화의 관습을 깨뜨린 혁신적인 작품으로 현대 미술의 출발점으로 평가됩니다.' },
    { id:'napoleon', title:'나폴레옹 대관식', artist:'자크 루이 다비드', year:'1807', country:'프랑스',
      url:'images/napoleon-coronation.jpg',
      desc:'신고전주의 화가 자크-루이 다비드가 그린 나폴레옹 1세의 대관식 장면입니다. 1804년 파리 노트르담 대성당에서 거행된 대관식을 기록한 대형 역사화로 가로 10미터에 달하는 거대한 작품입니다.' },
    { id:'creation', title:'아담의 창조', artist:'미켈란젤로', year:'1508~1512', country:'이탈리아',
      url:'images/creation-of-adam.jpg',
      desc:'르네상스의 거장 미켈란젤로가 바티칸 시스티나 성당 천장에 그린 프레스코화입니다. 신이 아담에게 생명을 불어넣는 순간을 표현한 장면으로 서로 향한 두 손가락은 세계에서 가장 유명한 이미지 중 하나입니다.' },
    { id:'fifer', title:'피리 부는 소년', artist:'에두아르 마네', year:'1866', country:'프랑스',
      url:'images/the-fifer.jpg',
      desc:'프랑스 화가 마네의 대표작으로, 군악대 소년이 피리를 부는 모습을 단순하고 강렬한 색채로 표현했습니다. 배경을 생략한 독특한 구도입니다.' },
    { id:'vgoghself', title:'자화상(반 고흐)', artist:'빈센트 반 고흐', year:'1889', country:'네덜란드',
      url:'images/vangogh-selfportrait.jpg',
      desc:'반 고흐가 생레미 요양원에서 그린 자화상으로 특유의 소용돌이치는 붓터치가 인상적입니다. 강렬한 눈빛과 단호한 표정에서 고흐의 예술적 의지가 느껴집니다. 평생 37점의 자화상을 남긴 고흐의 내면이 담긴 작품입니다.' },
    { id:'gleaners', title:'이삭 줍는 여인들', artist:'장 프랑수아 밀레', year:'1857', country:'프랑스',
      url:'images/gleaners.jpg',
      desc:'추수 후 밭에 떨어진 이삭을 줍는 세 여인을 그린 사실주의 걸작으로, 당시 하층 농민의 삶을 따뜻하게 담아낸 밀레의 대표작입니다.' },
    { id:'kiss', title:'키스', artist:'구스타프 클림트', year:'1907~1908', country:'오스트리아',
      url:'images/The_Kiss.jpg',
      desc:'꽃들이 만개한 풑밭에 서로 끌어 안은 한쌍의 여인의 모습입니다. 화려한 색과 문양이 환상적이고 신비로운 느낌을 줍니다.' },
    { id:'sleeping-gypsy', title:'잠자는 집시', artist:'앙리 루소', year:'1897', country:'프랑스',
      url:'images/sleeping-gypsy.jpg',
      desc:'달빛 아래 사막에서 잠든 집시 여인 곁에 사자가 서 있는 신비로운 장면을 담은 작품으로, 루소의 순수하고 독창적인 화풍이 돋보입니다.' },
    { id:'dream', title:'꿈', artist:'앙리 루소', year:'1910', country:'프랑스',
      url:'images/the-dream.jpg',
      desc:'코끼리, 뱀, 새, 오랑우탄이 있는 정글에 있는 붉은 소파 위에 한 여인이 누워 뱀을 부리는 사람이 연주하는 음악을 듣고 있는 모습을 담고 있습니다.' },
    { id:'las-meninas', title:'시녀들(라스 메니나스)', artist:'디에고 벨라스케스', year:'1656', country:'스페인',
      url:'images/las-meninas.jpg',
      desc:'스페인 궁정화가 벨라스케스의 걸작으로, 어린 공주 마르가리타와 시녀들, 화가 자신이 등장하는 복잡한 구도로 서양미술사 최고의 작품 중 하나로 꼽힙니다.' }
  ]
};